version: '3'
services:
  api:
    container_name: book-api
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c 'npm install; npm install -g nodemon ; nodemon -e js'
    networks:
      - nodeapp-network
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/nashamongo"

  mongo:
    container_name: nashamongo
    image: mongo
    command: mongod
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
